spring:
  data:
    mongodb:
      database: dyp
      host: 47.106.78.139
      port: 27017
  redis:
    database: 0
    host: 47.106.78.139
    port: 6379
    password: 123456
    timeout: 5000 #连接超时时间（毫秒）
    pool:
      max-idle: 4 #连接池中的最大空闲连接
      min-idle: 0 #连接池中的最小空闲连接
      max-active: 4 #连接池最大连接数（使用负值表示没有限制）
      max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制）
  datasource:
    url: jdbc:mysql://47.106.78.139:3306/mysql?useSSL=false&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    auto-commit: true
    maximum-pool-size: 8

server:
  port: 9901
  servlet:
    context-path: /admin
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain
