spring:
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/static,classpath:/resources/,file:C:/Users/Administrator/Desktop/
server:
  port: 8884
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain
#  ssl:
#    key-password: 123456
#    key-store: file:E:/spring.keystore
#    key-alias: spring
#    key-store-type: JKS