spring:
  redis:
    database: 12
    host: localhost
    port: 6379
    password:
    timeout: 5000
    pool:
      max-idle: 4
      min-idle: 0
      max-active: 4
      max-wait: -1
  datasource:
    url: jdbc:mysql://172.16.30.33:3309/mysql?useSSL=false&characterEncoding=utf-8
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    autoCommit: true
    maximumPoolSize: 8
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/static,classpath:/resources/,file:C:/Users/Administrator/Desktop/dy/dyp/dist
server:
  port: 9905
  servlet:
    context-path: /openapi
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain
openapi:
  rsaPublic: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCQT0cOIL11bsAXDc1FsZXbILiPJGAusvOcU+MiBnBPax9dKLi3s2J1X4Ih6aOpnrEht7Soh/iUPKODFIj2S/otWvRZL2xITDB7PObjm7BxWeVY8c38gtXwRTYfBSPUqqPxsS9wTGIw/QlXJZtyPCl4UUMmMS0+B/tUX9jV28/V+wIDAQAB
  rsaPrivate: MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAJBPRw4gvXVuwBcNzUWxldsguI8kYC6y85xT4yIGcE9rH10ouLezYnVfgiHpo6mesSG3tKiH+JQ8o4MUiPZL+i1a9FkvbEhMMHs85uObsHFZ5VjxzfyC1fBFNh8FI9Sqo/GxL3BMYjD9CVclm3I8KXhRQyYxLT4H+1Rf2NXbz9X7AgMBAAECgYAUmWxwJNZGjA+ZetvhZe8ZP3t4211rbRn/J65VbgvcGlN4zdZISq/0RzThOGOnU8K/KGT+ZaJjLqC8llLSrZfBaMP6ynqBxO1gF3Jhv4tHd4T9/ljOR3pFz9jcPcbv7quO+6MiKjFL80BPAR7eltf4WYYyuLQegvlw6jlNqLLRMQJBAMXMZ58wapVoqsL6ncuORn1d3PAVdYpxmP3pF+SlpJwFvI2nqBkwWIfnwvMS2gRUeCnXbxmBO7CwBM4VoioY4EkCQQC6xbcZYRpl1KzoFOeK3y1wc717ZCvIPeKXNz4q/wfCVpNL6wNasnwV5MtMgabdwiQLHD2KJO3skmGArkVYN8wjAkEAhFRU+u5EUELfA2Txjo5X4GWce06P/Zg0N6LrJkAfWXaJB+gjkP6ELCBEj6SMERuF7NBBdrm7+mA4Rru4axuLaQJAchPjUxgRRJNTDOn/xr2sBlxbJqu3ZjYOWWg/i4l71sKEc0FXKiWMTt8RIWirYBV9aF/WYrNNs0pxTWSkLE7gWwJBAKK80TiEHUQcG30bSbK2S4ImUj8+NEABQeDlh+v1C3SvZvmvrqOCJvEc9UGnJw1vUK8NXhHLOVUGe4JWvOhk1dA=

