spring:
  redis:
    database: 1
    host: 192.168.220.141
    port: 6379
    password: 123456
    timeout: 5000
    pool:
      max-idle: 4
      min-idle: 0
      max-active: 4
      max-wait: -1
  datasource:
    url: jdbc:mysql://192.168.220.141:3306/mysql?useSSL=false&characterEncoding=utf-8
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    autoCommit: true
    maximumPoolSize: 8
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/static,classpath:/resources/,file:C:/Users/Administrator/Desktop/dy/dyp/dist
server:
  port: 9902
  servlet:
    context-path: /customer
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain
openapi: dd
